In [1]:
import os
import json

In [6]:
dir1 = r"C:\Users\alyey\Git\BeyondLabels\output\runs\pathvul_run_logs"
unq = set()
for filename in os.listdir(dir1):
    if "except" in filename: continue
    with open(os.path.join(dir1, filename), "r") as f:
        data = json.load(f)
    unq.add(data["prompt_name"])
    if data["prompt_name"] == "prompt_1":
        data["prompt_name"] = "llmql"
    elif data["prompt_name"] == "prompt_2":
        data["prompt_name"] = "baseline"
    with open(os.path.join(dir1, filename), "w") as f:
        json.dump(data, f, indent=4)

In [4]:
import pandas as pd
df = pd.read_csv(r"C:\Users\alyey\Git\BeyondLabels\output\analysis\log_analysis\data\rq1_combined_refined_match.csv")
df

,CVE,runID,promptType,model,language,filename,outputFormat,outputLabel,actualLabel,nor,...,outputPathInd,realPath,outputPath,overlappingNodes,sourceHit,sinkHit,lcs_pathHash,lcs_outputPathIndex,lcs_real_range,lcs_output_range
0,CVE-2011-3211,claude_45_gpt-4o_run_CVE-2011-3211_bcfg2_20251...,baseline,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2011-3211_bcfg2_20251...,line,1,1,0.000000,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
1,CVE-2011-3211,claude_45_gpt-4o_run_CVE-2011-3211_bcfg2_20251...,llmql,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2011-3211_bcfg2_20251...,path,1,1,1.000000,...,0.0,"[{'line_number': 35, 'file_name': 'src/lib/Ser...","[{'role': 'source', 'file': 'src/lib/Server/Pl...","[(0, 4), (1, 4)]",True,True,ebd23f257182a4322c1780b118a2c6d7903c443517aa7d...,0.0,"(0, 1)","(4, 4)"
2,CVE-2012-3366,claude_45_gpt-4o_run_CVE-2012-3366_bcfg2_20251...,baseline,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2012-3366_bcfg2_20251...,line,1,1,0.000000,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
3,CVE-2012-3366,claude_45_gpt-4o_run_CVE-2012-3366_bcfg2_20251...,llmql,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2012-3366_bcfg2_20251...,path,1,1,1.000000,...,0.0,"[{'line_number': 35, 'file_name': 'src/lib/Ser...","[{'role': 'source', 'file': 'src/lib/Server/Pl...","[(4, 4), (2, 1), (0, 0), (1, 0), (3, 2)]",True,True,024d0c12d7377e3244aedeac185dd7e0fa1daa95484713...,3.0,"(0, 4)","(0, 4)"
4,CVE-2012-4520,claude_45_gpt-4o_run_CVE-2012-4520__01ce103cfa...,baseline,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2012-4520__01ce103cfa...,line,1,1,0.000000,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,CVE-2023-45278,claude_45_gpt-4o_run_CVE-2023-45278_yamcs_2025...,llmql,claude-sonnet-4-5,Java,claude_45_gpt-4o_run_CVE-2023-45278_yamcs_2025...,path,1,1,1.000000,...,2.0,"[{'line_number': 210, 'file_name': 'yamcs-core...","[{'role': 'source', 'file': 'yamcs-core/src/ma...","[(1, 1), (0, 0)]",True,True,a8a54baee8c624696decda56f8ffbab83b59168b6951a4...,2.0,"(0, 1)","(0, 1)"
205,CVE-2023-49109,claude_45_gpt-4o_run_CVE-2023-49109_dolphinsch...,baseline,claude-sonnet-4-5,Java,claude_45_gpt-4o_run_CVE-2023-49109_dolphinsch...,line,1,1,0.000000,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
206,CVE-2023-49109,ds_reasoner_gpt-4o_run_CVE-2023-49109_dolphins...,llmql,deepseek-reasoner,Java,ds_reasoner_gpt-4o_run_CVE-2023-49109_dolphins...,path,1,1,0.642857,...,1.0,"[{'line_number': 128, 'file_name': 'dolphinsch...","[{'role': 'source', 'file': 'dolphinscheduler-...","[(7, 4), (10, 5), (0, 0), (1, 1), (3, 3), (13,...",True,True,9fc3ae545fbffe31a6e992a8651582b6c9d0b604403f23...,1.0,"(0, 3)","(0, 3)"
207,CVE-2023-51770,claude_45_gpt-4o_run_CVE-2023-51770_dolphinsch...,baseline,claude-sonnet-4-5,Java,claude_45_gpt-4o_run_CVE-2023-51770_dolphinsch...,line,1,1,0.000000,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
208,CVE-2023-51770,ds_reasoner_gpt-4o_run_CVE-2023-51770_dolphins...,llmql,deepseek-reasoner,Java,ds_reasoner_gpt-4o_run_CVE-2023-51770_dolphins...,path,1,1,1.000000,...,0.0,"[{'line_number': 129, 'file_name': 'dolphinsch...","[{'role': 'source', 'file': 'dolphinscheduler-...","[(4, 3), (6, 6), (0, 6), (2, 3), (3, 3), (5, 3...",True,True,bfa1b941e1085b9d0c6bd2407d18e78fb48e2a3673fc77...,0.0,"(0, 1)","(6, 6)"

In [2]:
df_unique = df.loc[df.groupby(['CVE', 'promptType'])['nor'].idxmax()].reset_index(drop=True)
df_unique

,CVE,runID,promptType,model,language,filename,outputFormat,outputLabel,actualLabel,nor,...,outputPathInd,realPath,outputPath,overlappingNodes,sourceHit,sinkHit,lcs_pathHash,lcs_outputPathIndex,lcs_real_range,lcs_output_range
0,CVE-2011-3211,claude_45_gpt-4o_run_CVE-2011-3211_bcfg2_20251...,baseline,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2011-3211_bcfg2_20251...,line,1,1,0.000000,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
1,CVE-2011-3211,claude_45_gpt-4o_run_CVE-2011-3211_bcfg2_20251...,llmql,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2011-3211_bcfg2_20251...,path,1,1,1.000000,...,0.0,"[{'line_number': 35, 'file_name': 'src/lib/Ser...","[{'role': 'source', 'file': 'src/lib/Server/Pl...","[(0, 4), (1, 4)]",True,True,ebd23f257182a4322c1780b118a2c6d7903c443517aa7d...,0.0,"(0, 1)","(4, 4)"
2,CVE-2012-3366,claude_45_gpt-4o_run_CVE-2012-3366_bcfg2_20251...,baseline,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2012-3366_bcfg2_20251...,line,1,1,0.000000,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
3,CVE-2012-3366,claude_45_gpt-4o_run_CVE-2012-3366_bcfg2_20251...,llmql,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2012-3366_bcfg2_20251...,path,1,1,1.000000,...,0.0,"[{'line_number': 35, 'file_name': 'src/lib/Ser...","[{'role': 'source', 'file': 'src/lib/Server/Pl...","[(4, 4), (2, 1), (0, 0), (1, 0), (3, 2)]",True,True,024d0c12d7377e3244aedeac185dd7e0fa1daa95484713...,3.0,"(0, 4)","(0, 4)"
4,CVE-2012-4520,claude_45_gpt-4o_run_CVE-2012-4520__01ce103cfa...,baseline,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2012-4520__01ce103cfa...,line,1,1,0.000000,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,CVE-2023-45278,claude_45_gpt-4o_run_CVE-2023-45278_yamcs_2025...,llmql,claude-sonnet-4-5,Java,claude_45_gpt-4o_run_CVE-2023-45278_yamcs_2025...,path,1,1,1.000000,...,2.0,"[{'line_number': 210, 'file_name': 'yamcs-core...","[{'role': 'source', 'file': 'yamcs-core/src/ma...","[(1, 1), (0, 0)]",True,True,a8a54baee8c624696decda56f8ffbab83b59168b6951a4...,2.0,"(0, 1)","(0, 1)"
205,CVE-2023-49109,claude_45_gpt-4o_run_CVE-2023-49109_dolphinsch...,baseline,claude-sonnet-4-5,Java,claude_45_gpt-4o_run_CVE-2023-49109_dolphinsch...,line,1,1,0.000000,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
206,CVE-2023-49109,ds_reasoner_gpt-4o_run_CVE-2023-49109_dolphins...,llmql,deepseek-reasoner,Java,ds_reasoner_gpt-4o_run_CVE-2023-49109_dolphins...,path,1,1,0.642857,...,1.0,"[{'line_number': 128, 'file_name': 'dolphinsch...","[{'role': 'source', 'file': 'dolphinscheduler-...","[(7, 4), (10, 5), (0, 0), (1, 1), (3, 3), (13,...",True,True,9fc3ae545fbffe31a6e992a8651582b6c9d0b604403f23...,1.0,"(0, 3)","(0, 3)"
207,CVE-2023-51770,claude_45_gpt-4o_run_CVE-2023-51770_dolphinsch...,baseline,claude-sonnet-4-5,Java,claude_45_gpt-4o_run_CVE-2023-51770_dolphinsch...,line,1,1,0.000000,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
208,CVE-2023-51770,ds_reasoner_gpt-4o_run_CVE-2023-51770_dolphins...,llmql,deepseek-reasoner,Java,ds_reasoner_gpt-4o_run_CVE-2023-51770_dolphins...,path,1,1,1.000000,...,0.0,"[{'line_number': 129, 'file_name': 'dolphinsch...","[{'role': 'source', 'file': 'dolphinscheduler-...","[(4, 3), (6, 6), (0, 6), (2, 3), (3, 3), (5, 3...",True,True,bfa1b941e1085b9d0c6bd2407d18e78fb48e2a3673fc77...,0.0,"(0, 1)","(6, 6)"

In [5]:
df_unique[df_unique['promptType'] == "llmql"]

,CVE,runID,promptType,model,language,filename,outputFormat,outputLabel,actualLabel,nor,...,outputPathInd,realPath,outputPath,overlappingNodes,sourceHit,sinkHit,lcs_pathHash,lcs_outputPathIndex,lcs_real_range,lcs_output_range
1,CVE-2011-3211,claude_45_gpt-4o_run_CVE-2011-3211_bcfg2_20251...,llmql,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2011-3211_bcfg2_20251...,path,1,1,1.000000,...,0.0,"[{'line_number': 35, 'file_name': 'src/lib/Ser...","[{'role': 'source', 'file': 'src/lib/Server/Pl...","[(0, 4), (1, 4)]",True,True,ebd23f257182a4322c1780b118a2c6d7903c443517aa7d...,0.0,"(0, 1)","(4, 4)"
3,CVE-2012-3366,claude_45_gpt-4o_run_CVE-2012-3366_bcfg2_20251...,llmql,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2012-3366_bcfg2_20251...,path,1,1,1.000000,...,0.0,"[{'line_number': 35, 'file_name': 'src/lib/Ser...","[{'role': 'source', 'file': 'src/lib/Server/Pl...","[(4, 4), (2, 1), (0, 0), (1, 0), (3, 2)]",True,True,024d0c12d7377e3244aedeac185dd7e0fa1daa95484713...,3.0,"(0, 4)","(0, 4)"
5,CVE-2012-4520,claude_45_gpt-4o_run_CVE-2012-4520__256de7e29c...,llmql,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2012-4520__256de7e29c...,path,1,1,0.500000,...,2.0,"[{'line_number': 142, 'file_name': 'django/con...","[{'role': 'source', 'file': 'django/contrib/au...","[(2, 0), (3, 0)]",False,True,55904007dac97066b7c7730fc3cfadc3e334ff79bebd1b...,2.0,"(2, 3)","(0, 0)"
7,CVE-2013-0342,claude_45_gpt-4o_run_CVE-2013-0342_pyrad_20251...,llmql,claude-sonnet-4-5,Python,claude_45_gpt-4o_run_CVE-2013-0342_pyrad_20251...,path,1,1,1.000000,...,0.0,"[{'line_number': 211, 'file_name': 'pyrad/pack...","[{'role': 'source', 'file': 'pyrad/packet.py',...","[(1, 1), (3, 3), (2, 2), (0, 0)]",True,True,5ab23f50248ac2cbd727bc0800287e591347fd649d772b...,0.0,"(0, 3)","(0, 3)"
9,CVE-2014-125052,claude_45_gpt-4o_run_CVE-2014-125052_sparql-id...,llmql,claude-sonnet-4-5,Java,claude_45_gpt-4o_run_CVE-2014-125052_sparql-id...,path,1,1,0.625000,...,1.0,"[{'line_number': 33, 'file_name': 'src/main/ja...","[{'role': 'source', 'file': 'src/main/java/org...","[(3, 4), (6, 5), (0, 0), (1, 1), (2, 3)]",True,False,b75fd6f71e15825114b0eb5398dc0f0857af0fcbc2674c...,0.0,"(0, 1)","(0, 1)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,CVE-2023-45158,ds_reasoner_gpt-4o_run_CVE-2023-45158_web2py_2...,llmql,deepseek-reasoner,Python,ds_reasoner_gpt-4o_run_CVE-2023-45158_web2py_2...,path,1,1,1.000000,...,0.0,"[{'line_number': 36, 'file_name': 'gluon/messa...","[{'role': 'source', 'file': 'gluon/messageboxh...","[(1, 1), (2, 2), (0, 0)]",True,True,7a0fc7c47229112419c4521e6963286d5b7f6ea4fed2e4...,0.0,"(0, 2)","(0, 2)"
202,CVE-2023-45277,ds_reasoner_gpt-4o_run_CVE-2023-45277_yamcs_20...,llmql,deepseek-reasoner,Java,ds_reasoner_gpt-4o_run_CVE-2023-45277_yamcs_20...,path,1,1,0.750000,...,0.0,"[{'line_number': 165, 'file_name': 'yamcs-core...","[{'role': 'source', 'file': 'yamcs-core/src/ma...","[(1, 0), (2, 0), (0, 0)]",True,False,d217f428d9b2e164b0895877a01fe27f172ec80b00a4f5...,0.0,"(0, 2)","(0, 0)"
204,CVE-2023-45278,claude_45_gpt-4o_run_CVE-2023-45278_yamcs_2025...,llmql,claude-sonnet-4-5,Java,claude_45_gpt-4o_run_CVE-2023-45278_yamcs_2025...,path,1,1,1.000000,...,2.0,"[{'line_number': 210, 'file_name': 'yamcs-core...","[{'role': 'source', 'file': 'yamcs-core/src/ma...","[(1, 1), (0, 0)]",True,True,a8a54baee8c624696decda56f8ffbab83b59168b6951a4...,2.0,"(0, 1)","(0, 1)"
206,CVE-2023-49109,ds_reasoner_gpt-4o_run_CVE-2023-49109_dolphins...,llmql,deepseek-reasoner,Java,ds_reasoner_gpt-4o_run_CVE-2023-49109_dolphins...,path,1,1,0.642857,...,1.0,"[{'line_number': 128, 'file_name': 'dolphinsch...","[{'role': 'source', 'file': 'dolphinscheduler-...","[(7, 4), (10, 5), (0, 0), (1, 1), (3, 3), (13,...",True,True,9fc3ae545fbffe31a6e992a8651582b6c9d0b604403f23...,1.0,"(0, 3)","(0, 3)"
208,CVE-2023-51770,ds_reasoner_gpt-4o_run_CVE-2023-51770_dolphins...,llmql,deepseek-reasoner,Java,ds_reasoner_gpt-4o_run_CVE-2023-51770_dolphins...,path,1,1,1.000000,...,0.0,"[{'line_number': 129, 'file_name': 'dolphinsch...","[{'role': 'source', 'file': 'dolphinscheduler-...","[(4, 3), (6, 6), (0, 6), (2, 3), (3, 3), (5, 3...",True,True,bfa1b941e1085b9d0c6bd2407d18e78fb48e2a3673fc77...,0.0,"(0, 1)","(6, 6)"